import mongoose from "mongoose";

const customerSchema = new mongoose.Schema({
  _id: mongoose.Schema.Types.ObjectId,
  addresses: [Object],
  admin_graphql_api_id: String,
  created_at: Date,
  currency: String,
  default_address: Object,
  email: String,
  email_marketing_consent: Object,
  first_name: String,
  id: Number,
  last_name: String,
  last_order_id: String,
  last_order_name: String,
  multipass_identifier: String,
  note: String,
  orders_count: Number,
  phone: String,
  sms_marketing_consent: String,
  state: String,
  tags: String,
  tax_exempt: Boolean,
  tax_exemptions: [Object],
  total_spent: String,
  updated_at: Date,
  verified_email: Boolean,
});
